### ISSUE TITLE
Consider relicensing under tor-browser-build license

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/ncdns-repro#135]
We should consider relicensing this repo under [the tor-browser-build license](http://gzgme7ov25seqjbphab4fkcph3jkobfwwpivt5kzbv3kqx2y2qttl4yd.onion/builders/tor-browser-build.git/tree/LICENSE?id=27f5c69e971af1719b5106f6a62b72c4b79cd232).

**Comment by JeremyRand** [comment]
@hlandau Is relicensing under the tor-browser-build license okay for you?

**Comment by hlandau** [comment]
Go ahead.
