### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/ncdns-repro#61]
@domob1812 Can you enable the `ncdns-repro` repository for Travis builds?  You should be able to do so at https://travis-ci.org/namecoin/ncdns-repro .  I apparently don't have permissions to do it myself, since I'm not an admin of the Namecoin GitHub org.

**Comment by JeremyRand** [comment]
@domob1812 Actually it looks like I don't need admin permissions on the entire Namecoin org, I only need admin permissions on the ncdns-repro repository.  Can you give me that permission, so I can handle the Travis stuff myself?  (I think the reason I don't already have the permission is that this repo was transferred to the Namecoin org by Hugo, so the permissions are set differently.)

**Comment by domob1812** [comment]
@JeremyRand you should be an admin now.  Please reopen this if something still doesn't work as expected.
